# Generated by Django 5.0.6 on 2024-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TacoStandFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_revenue', models.FloatField()),
                ('daily_customers', models.IntegerField()),
                ('tacos_sold', models.IntegerField()),
                ('drinks_sold', models.IntegerField()),
                ('total_employee_hours', models.FloatField()),
            ],
        ),
    ]
